---

- name: Creating self-signed server SSL cert
  command: >
    openssl req -new -nodes -x509 -subj "/C={{ item.country|default('') }}/ST={{ item.state|default('') }}/L={{ item.city|default('') }}/O={{ item.organization|default('') }}/OU={{ item.unit|default('') }}/CN={{ item.name }}/emailAddress={{ item.email|default('') }}" -days {{ item.days|default(3650) }} -keyout {{ openssl_keys_path }}/{{ item.name }}.key -out {{ openssl_certs_path }}/{{ item.name }}.crt -extensions v3_ca
    creates={{ openssl_certs_path }}/{{ item.name }}.crt
  with_items: openssl_self_signed
  tags:
    - system
    - openssl
