---

- name: Checking dir exists
  stat: >
    path={{ item }}
  register: item_stat

- name: Creating directory
  file: >
    path={{ item }}
    owner=root
    group=root
    mode={{ mode }}
    state=directory
  when: not item_stat.stat.exists