---

- name: Installing packages for Debian
  when: ansible_os_family == 'Debian'
  apt: >
    pkg={{ item }}
    state=present
  with_items:
    - openssl
  tags:
    - system
    - openssl
    - install

- name: Installing packages for RedHat
  when: ansible_os_family == 'RedHat'
  yum: >
    name={{ item }}
    state=present
  with_items:
    - openssl
  tags:
    - system
    - openssl
    - install
