---

- include: install.yml
  tags:
    - system
    - openssl
    - openssl-install

- include: config.yml
  tags:
    - system
    - openssl
    - openssl-config

- include: create.yml
  tags:
    - system
    - openssl
    - openssl-create

- include: copy.yml
  tags:
    - system
    - openssl
    - openssl-copy
